import OneCard from "./OneCard";
import TwoCard from "./TwoCard";
import ThreeCard from "./ThreeCard";
import FourCard from "./FourCard";
import FiveCard from "./FiveCard";
import SixCard from "./SixCard";
import SevenCard from "./SevenCard";
import EightCard from "./EightCard";
import NineCard from "./NineCard";
import TenCard from "./TenCard";
import ElevenCard from "./ElevenCard";
import TwelveCard from "./TwelveCard";
import ThirteenCard from "./ThirteenCard";
import FourteenCard from "./FourteenCard";
import FifteenCard from "./FifteenCard";
import SixteenCard from "./SixteenCard";
import SeventeenCard from "./SeventeenCard";
import EighteenCard from "./EighteenCard";

const Cards = [
  { card: <OneCard/> },
  { card: <TwoCard/> },
  { card: <ThreeCard/> },
  { card: <FourCard/> },
  { card: <FiveCard/> },
  { card: <SixCard/> },
  { card: <SevenCard/> },
  { card: <EightCard/> },
  { card: <NineCard/> },
  { card: <TenCard/> },
  { card: <ElevenCard/> },
  { card: <TwelveCard/> },
  { card: <ThirteenCard/> },
  { card: <FourteenCard/> },
  { card: <FifteenCard/> },
  { card: <SixteenCard/> },
  { card: <SeventeenCard/> },
  { card: <EighteenCard/> },
];
export default Cards
