const Titles = [
  { title: "少年野球連盟HP" },
  { title: "株式会社J-REP HP" },
  { title: "合同会社キッカケ HP" },
  { title: "キッカケ専用販売 HP" },
  { title: "パワーグレード販売 LP" },
  { title: "WEB制作ゼロイチ HP" },
  { title: "RIBREC LP" },
  { title: "eyecarelabo LP" },
  { title: "株式会社 Vie Huit LP" },
  { title: "ゼロワン LP" },
  { title: "現在作成中 HP" },
  { title: "株式会社ITプラス HP" },
  { title: "オレンジグループ HP" },
  { title: "ITカリキュラム 1" },
  { title: "ITカリキュラム 2" },
  { title: "ITカリキュラム 3" },
  { title: "ITカリキュラム 4" },
  { title: "ITカリキュラム 5" },
];
export default Titles;
